### ISSUE TITLE
fix(incentives): error message

### ISSUE THREAD

**Issue by Sen-Com** [White-Whale-Defi-Platform/white-whale-frontend#302]
The creation of incentives can fail for multiple reasons for example:
- not enough whale in wallet
- flow start too far in the future
- flow end too far in the future
- flow duration too long

That should be communicated to the user via the (disabled) primary button

**Comment by jijicodes** [comment]
Hey @Sen-Com 
I am open to work on this ticket if it's still needed. It looks like this ticket has been open for a while.
However I want to clarify a few things before I move forward with this issue.

![Screenshot 2024-03-05 at 2 37 24 PM](https://github.com/White-Whale-Defi-Platform/white-whale-frontend/assets/69917943/eef3fd53-b322-4784-992f-c710b6c76f28)

`https://app.whitewhale.money/[chain]/pools/incentivize?poolId=[pool]`
is this page the one that needs to be fixed?

> not enough whale in wallet

 Does this refer to the fact that the minimum should be more than 1000 whale to create incentives (1000 whale creation fee + incentives) or something else? 

> flow start too far in the future
> flow end too far in the future
> flow duration too long

How do i know these limits and where would I look them up?
 
> That should be communicated to the user via the (disabled) primary button
If I understand this correctly, you don't want me to display to the user why the form is invalid.
Just disable the submit button

**Comment by nick134-bit** [comment]
"Does this refer to the fact that the minimum should be more than 1000 whale to create incentives (1000 whale creation fee + incentives) or something else?"
Yes, a info for the fee is needed as well. Something like this:

![image](https://github.com/White-Whale-Defi-Platform/white-whale-frontend/assets/76399455/35c36c64-322a-4e31-b8d4-a1958579aa73)


the limits are defined by failed simulations:

e.g: "to execute message; message index: 0: Flow start timestamp is too far into the future:"

Would be nice to show a short reason as the button label and deactivate the button. Like we have it on the swap page if the slippage is too high.

**Comment by jijicodes** [comment]
> The creation of incentives can fail for multiple reasons for example:
> 
> * flow end too far in the future
> * flow duration too long

![Screenshot 2024-03-07 at 2 09 15 PM](https://github.com/White-Whale-Defi-Platform/white-whale-frontend/assets/69917943/7ef508bd-0cf0-467c-8734-d280471c8b33)
<img width="823" alt="Screenshot 2024-03-07 at 2 24 40 PM" src="https://github.com/White-Whale-Defi-Platform/white-whale-frontend/assets/69917943/059566c0-c3de-4022-9b0a-f6b77a94066c">

![Screenshot 2024-03-07 at 2 12 04 PM](https://github.com/White-Whale-Defi-Platform/white-whale-frontend/assets/69917943/b02fc139-7b55-403e-ad9c-ed9bd3055569)

Seems that the contract doesn't error with a very far away end date or giant flow duration (or also start date in the past). Unless you guys want otherwise I'll omit those errors from this bugfix.
