### ISSUE TITLE
subtract tx fees from tx funds 

### ISSUE THREAD

**Issue by nick134-bit** [White-Whale-Defi-Platform/white-whale-frontend#464]
Currently the max button on AssetInput is using 100% of the users funds. If this is the fee currency the tx fails with not enough funds.

If you want to report a security issue, please follow our security policy: `https://github.com/White-Whale-Defi-Platform/migaloo-frontend/blob/main/docs/SECURITY.md`

---

## Steps to Reproduce

1. Navigate to `P` page and begin to
2. Execute `X` transaction on the `vault` contract 
3. ... 
4. ... 

**Expected results:** 

**Actual results:** 

---

### Additional context

Add any other context about the problem here, code snippets, json responses and so on.

<details>
<summary>Screen shots</summary>

</details>

<details>
  <summary>Logs</summary>

```

```

</details>

**Comment by jijicodes** [comment]
> ### Steps to Reproduce
> Navigate to P page and begin to
> Execute X transaction on the vault contract
> ...
> ...
> Expected results:
> 
> Actual results:

Hey @nick134-bit, I would be happy to try to tackle this issue however I am unsure if I am understanding correctly. 
I went to the production site and attempted to swap all of my whale token to usdc and the ui display shows that the maximum i could use was 0.1 WHALE less than my max balance and it showed the transaction as a success but I know that the tx actually failed (since the actual gas fee was 0.5 WHALE). Are we talking about this bug in this issue? If so I can take a look but I'm a bit unsure how I could calculate the true gas fee to make the max button function accurately.

![Screenshot 2024-03-05 at 1 51 32 PM](https://github.com/White-Whale-Defi-Platform/white-whale-frontend/assets/69917943/b966eb32-fa8d-4929-8082-60d11919bdd7)

**Comment by nick134-bit** [comment]
Hey @jijicodes, 
correct, we currently use 0.1 as hardcoded gas fee value. Maybe its possible to simulate the tx fee before and make sure the user still got enough funds for more than one tx after the swap. This results in dust but better UX than stuck on a chain with no funds for fees IMO.

**Comment by jijicodes** [comment]
> Maybe its possible to simulate the tx fee before 

Hey, @nick134-bit.
I found the `useSimulate` hook in the codebase but i don't think this is for the simulated gas. Do you happen to know if there is an existing hook specific for querying the simulated gas?
